# Generated by Django 4.2 on 2025-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
