# Generated by Django 4.2 on 2025-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Text',
        ),
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
